### ISSUE TITLE
Update meta.json with meta-tags

### ISSUE THREAD

**Issue by jketreno** [MinnowBoard-org/website#103]
The file [meta.json](https://github.com/MinnowBoard-org/website/blob/master/meta.json) is now ready to be populated with the meta-tags and open graph protocol tags for the website.

@adreanneb The only trick is making sure to escape the strings correctly. Use single apostrophe (') for the field separators, and double quote (") to enclose the full tag. For example:

```json
[ {
  "pattern": "/get-a-board/?*",
  "meta-tags": [
    "name='description' content='Ready to buy a MinnowBoard?'",
    "property='og:title' content='MinnowBoard: Get a Board'"
  ]
} ]
```
**NOTE**: There is no comma at the end of the last `meta-tags` entry.

I put in top level placeholders for each of the main site pages.

The above strings are injected into the main web page wrapped in `<meta-tag STRING />`.

If invalid JSON syntax is pushed, the staging server won't load correctly; you can tweak and re-push a new version and once it's valid, the site will come back online.

**Comment by ebrent8** [comment]
I'm completing this and adding the og meta image also.

**Comment by ebrent8** [comment]
Fixed and on STG.  JSON is valid.  Unable to test it though.  Since it's a single-page app, right clicking to see the source to see if the meta tags are there, doesn't work.

The free online testers didn't return anything.  http://opengraphcheck.com/

Can you test that it's working correctly @jketreno ?  Thank you.

**Comment by dbkinder** [comment]
If the document's title is set with a <title>...</title> tag (or updated after loading with JavaScript), you should see the name on the tab change to be that title.  When I wander around stg.minnowboard.org I don't see the name in the tab changing (it says MinnowBoard.org all the time).  That would indicate that the title is not being changed as you go from page to page...

**Comment by ebrent8** [comment]
Yeah I can't verify on STG that it's working correctly.   Thx.

**Comment by dbkinder** [comment]
Not sure if this is the problem but the url for the Get a board page is https://stg.minnowboard.org/get-a-board  and the pattern shown in the first comment above is "pattern": "/get-a-board/?*".  Since there's no trailing slash on the url could that be an issue (should the pattern be "pattern": "/get-a-board") ?

**Comment by dbkinder** [comment]
Also, while "view source" may not work, "inspect element"(in chrome) should show you the actual generated web page HTML

**Comment by ebrent8** [comment]
Yeah good catch.  @jketreno is the pattern correct with the trailing slash?

**Comment by dbkinder** [comment]
Here's a fragment from the console log in the browser when loading the get a board page:

Route changing tab from get-a-board to get-a-board
GA: /get-a-board
Route changed to: "/get-a-board"
Route changing tab from get-a-board to get-a-board
GA: /get-a-board
Tab changed to: get-a-board
Fetching pages/get-a-board/get-a-board-intro.md
Fetching pages/get-a-board/get-a-board-after.md
Fetching pages/get-a-board/get-a-board.md

**Comment by jketreno** [comment]
> Not sure if this is the problem but the url for the Get a board page is https://stg.minnowboard.org/get-a-board and the pattern shown in the first comment above is "pattern": "/get-a-board/?*". Since there's no trailing slash on the url could that be an issue (should the pattern be "pattern": "/get-a-board") ?

The meta-tag information is only updated when navigating to pages via URLs, the same way SEO systems access the sites -- not by clicking around the site.

The tags are intended to assest open graph social media embedding and SEO ranking. They weren't design to change the HTML <title> element, which is static to "MinnowBoard.org".

**Comment by ebrent8** [comment]
OK.  If it's 'as designed' then cool.   I trust that it's working correctly.  Thx.
