### ISSUE TITLE
add license files to /design-files repo folders

### ISSUE THREAD

**Issue by BrianOttaway** [MinnowBoard-org/website#106]
License files need to be added to each applicable folder with design files repo.

My thought is that this .txt should probably exist in each folder underneath the the fab. This accommodates the event where a later vendor provides, say, a translation of CAD database into their tool for us to post…(from their view it encourages developers to use their software). Since this is a different vendor, we should require and accommodate a distinct clear license from them. In most cases, I'd envision that we convince said vendor to just adopt our standard CC-BY license text file...since that is our default policy...but I'd like to leave the door open if needed for some unique, valuable case.

#### Example:

Board name XYZ
- PCB version #
   - Gerbers
      -License.txt
   - BOM
      -License.txt
   - Database A
      -License.txt
   - Database B
      -**License.txt or License 2.txt**

**Comment by ebrent8** [comment]
What is the license file?  I'd like to get this ticket and related ones completed today.  I don't know what it should say.  Who does?

**Comment by BrianOttaway** [comment]
I created a license guidance file under the /design-files [root](https://github.com/MinnowBoard-org/design-files/blob/master/license-guidance.md). 

I will then create a few example license.txt files according to that guidance. In short, the content of the license.txt file should exactly replicate the license that the submitting partner granted.

**Comment by BrianOttaway** [comment]
I just completed the license.md for turbot PCB revF200. This is done. 

@ebrent8 : when you post the MinnowBoard-max/a1 and /a2 I can copy over nearly the same license.md...just need to adjust the attribution reference and future attribution reference. 

OK?

**Comment by ebrent8** [comment]
OK I'll read it and learn.  But I am not familiar with these OS licenses and just not sure exactly what belongs where.  I will read the ticket and your instructions and follow those.

**Comment by ebrent8** [comment]
What do you mean when I post the max a1 a2?  Am I pulling that off the wiki and putting those in the design files too?

**Comment by ebrent8** [comment]
OK a1 and a2 complete.
https://github.com/MinnowBoard-org/design-files

Is that it?  You got the license action from here?

**Comment by BrianOttaway** [comment]
just posted license.md files for both max-a1 and -a2. Please double check. Anything else?

**Comment by ebrent8** [comment]
I see those but they didnt render correctly for me when clicking on them.  Maybe because I'm a member.  Also do you need the .md file type on there?
<img width="601" alt="screen shot 2017-02-01 at 1 17 54 pm" src="https://cloud.githubusercontent.com/assets/18618930/22526683/0a7a755e-e881-11e6-96b3-a35fcf60a818.png">

**Comment by BrianOttaway** [comment]
they are rendering for me just fine. Are you sure you are clicking the actual license file and not the commit message?
![image](https://cloud.githubusercontent.com/assets/22825861/22527127/d93cd192-e882-11e6-8a87-24fafa246369.png)

**Comment by ebrent8** [comment]
yes duh, my bad.  That's what I was doing.  Ok this sucker is closed and completed.
