### ISSUE TITLE
"Explore the Board" links should all go to the same place

### ISSUE THREAD

**Issue by dbkinder** [MinnowBoard-org/website#11]
On the minnowboard.org home page there are five links to "Explore the Board" (maybe a bit overkill) and all go the http://minnowboard.org/board-viewer except for one that goes to http://minnowboard.org/learn-more/high-level-technical-specifications.  I'd expect links with the same words would go to the same place.  Perhaps the one that goes to the high level specs should be named differently.

**Comment by ebrent8** [comment]
Fixed this on STG.  It will go out with the next push on Friday , hopefully.
https://stg.minnowboard.org/

**Comment by ebrent8** [comment]
verified in PROD
