### ISSUE TITLE
review Windows 10 tutorial

### ISSUE THREAD

**Issue by ebrent8** [MinnowBoard-org/website#111]
I created a new Win 10 tut.  It's on STG.  Please review it and reword anything to keep with our content tone etc.  Thx.

https://stg.minnowboard.org/tutorials/

**Comment by ebrent8** [comment]
@BrianOttaway I made a WIN 10 tut.  See link above.  I didnt mention the board type, since it should work for the MB3 and if all our references are to turbot, especially titles, they will all have to change in the future.  Which means changing links etc.  What say you?  Cool as is?

**Comment by BrianOttaway** [comment]
I say: "Cool as-is"! Take it to prod.

**Comment by ebrent8** [comment]
ok @adreanneb it should be on STG.  Refresh browser page to be sure you see the latest.

Thx 'tiger-team' @BrianOttaway !
