### ISSUE TITLE
Create Button style

### ISSUE THREAD

**Issue by adreanneb** [MinnowBoard-org/website#120]
Please make us a green button like the one below in GitHub. (It will be an href link to Github issues from the Get help page.) 
![image](https://cloud.githubusercontent.com/assets/24276479/22570069/c0213000-e94e-11e6-8c4d-a63f9c0522f4.png)

**Comment by dbkinder** [comment]
If you haven't found it yet, there's an easy CSS button generator here: http://css3buttongenerator.com/ 
But, do you want a green button, or a GitHub icon for the link?

**Comment by ebrent8** [comment]
I believe that Julio is integrating it into markdown for us as per Adreanne's request.

**Comment by dbkinder** [comment]
oops.  Sorry about closing the issue, I meant to cancel my comment :(

**Comment by ebrent8** [comment]
It's cool.  No problem.  Thanks for looking through the bugs and having solutions - appreciate it!

**Comment by juliocri** [comment]
@adreanneb, @ebrent8  I'm working on this and I found that class addition is not working  for links, but regardless that we can do a trick to make it happen.  below i let you a couple of examples that we can try:

ADDING A CLASS TO THE END OF A PARAGRAPH AND ALL LINKS INSIDE CAN BE TREATED WITH THE SAME CLASS:

```markdown
The MinnowBoard mailing list has been in place since the first MinnowBoard design,
and has attracted a group of expert community developers that not only pose great
questions, but also provide solutions. If you prefer, you can join the [MinnowBoard mailing list](http://lists.elinux.org/mailman/listinfo/elinux-minnowboard) and ask your question there.{btn-sm}
```

ADDING LINKS IN SINGLE LINES AND PUTTING THE CLASS AT THE END OF THE LINE:

```markdown

[MinnowBoard mailing list](http://lists.elinux.org/mailman/listinfo/elinux-minnowboard){btn-sm class-1}

[MinnowBoard mailing list](http://lists.elinux.org/mailman/listinfo/elinux-minnowboard){btn-sm class-2}
```

basically in the second example we are forcing to the link be inside a single paragraph, what do you think?

**Comment by ebrent8** [comment]
That works for me.  Pretty simple.  Thanks, let's try it.

**Comment by juliocri** [comment]
@ebrent8 , @adreanneb I just sent the styles to master, the class you need to use is: ```.btn-green```

**Comment by adreanneb** [comment]
thanks @juliocri !

**Comment by ebrent8** [comment]
Let's wait till its live on PROD until we close this.

**Comment by ebrent8** [comment]
Looks great on STG Julio.  Good job and thanks !

**Comment by juliocri** [comment]
@dbkinder just sent a commit removing duplicated styles for the button 👍
