### ISSUE TITLE
embed video solution

### ISSUE THREAD

**Issue by ebrent8** [MinnowBoard-org/website#129]
In the near future, we shall need embeded videos for tutorials etc.
One easy solution I was thinking was to have them hosted on our own YouTube channel and then embed as needed like this : http://embedresponsively.com/

This would solve:
- streaming video type headache
- responsive and quality for mobile/desktop headache
- have another place where people could find out about us
- help with SEO by having rich content around the web

We would just need to be able to embed an iframe in markdown.  Maybe we could make an easy image-like tag where we just need to put the URL in?

What do ya think?  We don't need it soon, but maybe by the middle of March?

**Comment by juliocri** [comment]
I think I need I little bit time in this to take a look if there is a some stable plugin to the markdown that can be added easily otherwise this will be something pretty custom developed by us.

**Comment by ebrent8** [comment]
If we hosted our videos at YouTube, I would hope to be able to either have an HTML tab that we could paste in HTML iFrame like above or get a custom MD tag.

**Comment by juliocri** [comment]
@ebrent8 I just pushed some changes to the markdown renderer in order to put youtube videos, is easy only need to know the video id and put a 1 markdown line such the next one: ```![@youtube](ehEN-0CAp2U)``` I also puto some examples in https://stg.minnowboard.org/markdown-style-guide/youtube-video-embedding

**Comment by ebrent8** [comment]
Very nice!  Yeah that's way cool.  Thank you.

**Comment by ebrent8** [comment]
verified in PROD
