### ISSUE TITLE
Link to component spec sheet…and mouser/digikey order link. 

### ISSUE THREAD

**Issue by BrianOttaway** [MinnowBoard-org/website#130]
Idea was provided during Android Things prep meeting. Website needs to have links to component specs and ideally mouser/digikey/etc order links. 

Brian's view: 
- this could be done directly in board viewer. click on a part and second line shows Primary & alternate Mfr and MPN, next to order link. This is a lot of work to keep current.
- second option is to keep the info updated in the product BOM spreadsheet that is in the design-files repo.

**Comment by ebrent8** [comment]
I like the second option

**Comment by BrianOttaway** [comment]
in that case the board explorer comp files should have a standard link and text over to the design files repo, like the below for Turbot explorer: 

> For Component manufacturer, part number, alternates and order links, see product bill of materials (BOM) located in [design-files repo](https://github.com/MinnowBoard-org/design-files). Drill down to your target MinnowBoard product name, and Fab Revision...the BOM folder/file is within.

**Comment by ebrent8** [comment]
Do you mean that we put that text (above) with link in the left-hand side of the page?
<img width="755" alt="screen shot 2017-02-10 at 9 44 24 am" src="https://cloud.githubusercontent.com/assets/18618930/22837481/a2d2c5ea-ef75-11e6-81e2-767daddd9832.png">

**Comment by BrianOttaway** [comment]
I wasn't talking about putting the text there at top left...but it does seem like a better idea...instead of putting it into every single unique component explorer file. Perhaps in your suggestion we could shorten it to be another line in bold blue text: Design Files and BOM in Github

**Comment by ebrent8** [comment]
Yeah lets not put it on every explorer file.  If you can shorten it, I'll put it in there.  It already mentions schematic and design files.  Easy to fit that in with the link.  Tell me what you want it to say and I'll add it now.  Thx.

**Comment by BrianOttaway** [comment]
- Implementation on stage looks good. 
- Let's just skip the 2nd part of the issue "mouser/DK order link"...has lower value.

**Comment by ebrent8** [comment]
verified in PROD
