### ISSUE TITLE
Create alternate firmware tutorial

### ISSUE THREAD

**Issue by adreanneb** [MinnowBoard-org/website#139]
Using info from wiki, create alternate firmware tutorial.

**Comment by adreanneb** [comment]
@BrianOttaway  @ebrent8 am I talking about MB MAX, Turbot, or both for this tutorial?

**Comment by adreanneb** [comment]
@BrianOttaway  Also, besides Coreboot, the others don't really seem to exist anymore. Sage went out of business, WinZent no longer returns anything for MinnowBoard, and UBoot maybe but I need your opinion.

**Comment by adreanneb** [comment]
@BrianOttaway @ebrent8 It says this is an auto generated file, but from where: http://wiki.minnowboard.org/images/c/cd/Minnowboard_Max_Coreboot_config.txt
Can I just copy it into a new file?

**Comment by ebrent8** [comment]
Yeah copy or save it as a text file.

**Comment by BrianOttaway** [comment]
Adreanne and I reviewed offline. She already had the right stuff headed to markdown.

**Comment by adreanneb** [comment]
@ebrent8 @BrianOttaway  Ready for your review: https://stg.minnowboard.org/tutorials/alternate-firmware

**Comment by ebrent8** [comment]
Looks great.  I added horizontal rules between different firmware titles just to separate them visually.  Awesome fast work @adreanneb !!

**Comment by BrianOttaway** [comment]
Are the headers established to automatically populate the left side nav?

**Comment by adreanneb** [comment]
Heading level three are

**Comment by BrianOttaway** [comment]
we're set then.

**Comment by dbkinder** [comment]
There are some formatting/typos that should be fixed:

- Under "Install the dependencies" the two command lines there should be just one
   ```
   $ sudo apt-get install gcc git make ncurses-dev flex bison
   ```

- Under "Get Intel Firmware Support Package" you say to download either a Windows or Linux version, but then provide three choices (I don't know what the third choice is).

- Under "Setup Firmware Support Package", the [this guide](...) linking notation isn't the right markup, and the commandline block is indented too far and is badly formatted.  Also this text about MinnowBoard MAX might be confusing for Turbot users.

- Has anyone actually verified these Coreboot instructions (with editing and patching line 127) is still technically accurate?

- Not sure if the WinZent boot times are still meaningful and accurate.

**Comment by ebrent8** [comment]
???? Some of these look fixed to me on STG.
1.  I see them as two lines.
<img width="849" alt="screen shot 2017-02-08 at 4 35 36 pm" src="https://cloud.githubusercontent.com/assets/18618930/22763994/b3f505f4-ee1c-11e6-8b9e-87647579a563.png">

**Comment by dbkinder** [comment]
the example you show should be one line, not two :)

**Comment by ebrent8** [comment]
Ohhhhhhhhhhhhh  gotcha

**Comment by ebrent8** [comment]
If you want to fix the other things or test the firmware or answer questions in the other bugs, please join in the fun.  Thx.

**Comment by dbkinder** [comment]
Not enough hours in the day with all the other projects I'm working on ... but thought I'd do a quick look on some of these going by...

**Comment by ebrent8** [comment]
verified in PROD
