### ISSUE TITLE
Update "About" page text to: 

### ISSUE THREAD

**Issue by BrianOttaway** [MinnowBoard-org/website#143]
Update "About" page text to: 

>The MinnowBoard.org Foundation is a US-based non-profit providing education and promotion of the design and use of open-source software and hardware in embedded computing, on Intel® Architecture. MinnowBoard.org supports the Open Source Hardware Association (OSHWA.org) principles and makes its designs publicly available so "anyone can study, modify, distribute, make, and sell the design or hardware based on that design." MinnowBoards are designed to offer exceptional performance, flexibility, openness, and standards. These embedded boards have an enormous range of capabilities for hardware, software, and firmware developers: from creating a fun hobby or professional maker project, to evaluating SoCs and developing high performance embedded applications or products

**Comment by adreanneb** [comment]
@BrianOttaway  ok? https://stg.minnowboard.org/about

**Comment by BrianOttaway** [comment]
Looks good to me. I forwarded to Jim just for sanity check…but since he wrote it…. ☺

**Comment by ebrent8** [comment]
verified in PROD
