### ISSUE TITLE
Add to "optional accessories" on /get-a-board page

### ISSUE THREAD

**Issue by BrianOttaway** [MinnowBoard-org/website#158]
Add Standoffs, screws, rubber feet to Optional accessories list. I purchased stainless steel options below...will confirm and then we can add to site. 

- Standoffs: 
  - Female aluminum Standoffs at [McMaster-Carr](https://www.mcmaster.com/#female-threaded-round-standoffs/=16lgm1q). Aluminum is ideal for securing expansion cards to the top-side Low Speed Expansion (LSEv1) or secondary side High Speed Expansion (HSEv1), if applicable. Aluminum is also a good choice for sturdy feet to keep your board off the desk surface, helping to prevent shorts and other damage.
      - Recommended ==> Thread = 6-32, Material = Aluminum, Outside Diamater (OD) = 1/4", Shape = Round. Then select desired length:
         - [1" Length](https://www.mcmaster.com/#93330A449). Some people prefer a taller standoff for desktop feet. Often paired with rubber feet.
         - [5/8" Length](https://www.mcmaster.com/#93330A446). This is the right length for mounting top-side LSEv1 expansion cards (Lures). For most people 5/8" is also the preferred length for desktop feet, often paired with rubber feet. As you can see by inspecting the height of bottom side components, other standoffs may work. 
  - Female threaded standoffs at [Mouser](http://www.mouser.com/Electromechanical/Hardware/Standoffs-Spacers/_/N-aictf/). Many choices available from Mouser too. Apply the same filters. [5/8" length, Alum](http://www.mouser.com/ProductDetail/RAF-Electronic-Hardware/1686-632-AL/?qs=sGAEpiMZZMtrde5aJd3qw0AN1sweODAOXwba0jzYDXA%3d). [1" length, Alum](http://www.mouser.com/ProductDetail/RAF-Electronic-Hardware/1692-632-AL/?qs=sGAEpiMZZMtrde5aJd3qw4906qPZKIlyLaZZgp%2ffwe4%3d)
- Rubber Feet: We like to attach [rubber feet](https://www.mcmaster.com/#9540k693/=16a7i3d) to the bottom of standoffs that will sit on the desktop surface, to prevent sliding around. Entirely optional, but it gives a good feel.  Many options available. Look for a "counterbore" of 1/4" to match the standoffs and screws.
- Standoff/Nut Kits: These are a cheap way to get the standard lengths in Nylon material.  
  - amazon nylon kit: https://www.amazon.com/dp/B01EPLH08Y/ref=psdc_16409981_t3_B01I0SORIE?th=1
  - Amazon nylon kit: https://www.amazon.com/180Pcs-M3-Hex-Spacers-Screw-Nut-Standoffs-Quadcopter-Drone-Raspberry/dp/B01I0SORIE/ref=sr_1_1?ie=UTF8&qid=1486673441&sr=8-1&keywords=board+standoffs
- Screws: 
  - https://www.mcmaster.com/#91735a144/=16a7htg
  - http://www.mouser.com/ProductDetail/Keystone-Electronics/9903/?qs=sGAEpiMZZMtFmYSM%2fWUJwjMM2jkmYE8TU%252b6NUFYxuNE%3d

**Comment by ebrent8** [comment]
On hold till @BrianOttaway reviews these.  Then reassign to brent.

**Comment by BrianOttaway** [comment]
see above...this work @ebrent8 ? It is a bit more of a story, because there are options depending on what they are looking for.

**Comment by ebrent8** [comment]
Yeah let's talk about how to organize it on the 'get a board' page and i'll get it on this week.

**Comment by ebrent8** [comment]
@BrianOttaway Let's talk about the best way to organize these on the 'get a board' page after our meeting tomorrow.

**Comment by ebrent8** [comment]
verified in PROD

**Comment by ebrent8** [comment]
OK new stand-off text and links are on STG.  I checked the new links, but you may want to double check me too.  @BrianOttaway thx.
https://stg.minnowboard.org/get-a-board

**Comment by BrianOttaway** [comment]
looks good. checked links too.

**Comment by ebrent8** [comment]
in prod
