### ISSUE TITLE
add warranty info to /help

### ISSUE THREAD

**Issue by BrianOttaway** [MinnowBoard-org/website#161]
Add below "warranty information" to the /help page, with appropriate header so it shows up in left nav. My thought is that it should go at the bottom of the page, as most people are not going to the page for warranty info.
>Inquiries for technical support, warranty or RMA requests should be directed to the business or distributor from whom the product was purchased.

**Comment by ebrent8** [comment]
k i got it

**Comment by ebrent8** [comment]
on STG
https://stg.minnowboard.org/help

**Comment by BrianOttaway** [comment]
great.

**Comment by ebrent8** [comment]
verified in PROD
