### ISSUE TITLE
Update wiki firmware pages with redirect URLs

### ISSUE THREAD

**Issue by BrianOttaway** [MinnowBoard-org/website#167]
After issue #139 is pulled into production, update all the firmware wiki pages to delete current text and simply add referral URL. 
1. http://wiki.minnowboard.org/UEFI 
   1. Change to: "Refer to [https://minnowboard.org/tutorials/updating_your_firmware](Update The Firmware) tutorial.
   1. Update firmware tutorial to remove last line reference back to Wiki
1. http://wiki.minnowboard.org/Coreboot, http://wiki.minnowboard.org/SageBIOS, http://wiki.minnowboard.org/U-Boot, http://wiki.minnowboard.org/WinZent
   1. Change to: "Refer to _Alternate-Firmware-Tut-URL"

FYI: @ebrent8

**Comment by adreanneb** [comment]
Done.
