### ISSUE TITLE
Need a 404/missing page error response

### ISSUE THREAD

**Issue by dbkinder** [MinnowBoard-org/website#17]
If you reference a non-existent page such as minnowboard.org/adfasdf you get a blank page with just a site header on it:

![image](https://cloud.githubusercontent.com/assets/11063618/20845285/2f0c4fa6-b879-11e6-8b96-798a442aa6c6.png)

**Comment by ebrent8** [comment]
Please create a blank page modeled after the home page template and we'll fill in the content.  Thx.

**Comment by juliocri** [comment]
Hey we have implemented a rustic message of error when the page is not found in minnow site, only styles and customisation for the message (in markdown) is missing.

**Comment by ebrent8** [comment]
OK excellent.  What's the page name in GitHub and location?  Thx !

**Comment by ebrent8** [comment]
I found it, thanks.  it's on STG now and looks good.
