### ISSUE TITLE
Test Entry: External new user

### ISSUE THREAD

**Issue by brottawa** [MinnowBoard-org/website#2]
**## TEST.**
I am getting a 404 error when I try to access this page (LINK). Can you please advise? @jketreno @BrianOttaway

**Comment by jketreno** [comment]
> I am getting a 404 error when I try to access this page (LINK). 

Which link are you trying to access?

Also, syntax for embedding a link is  ```[title-in-brackets](url-in-parenthesis)``` 

For example:

```[ketrenos.com](https://ketrenos.com)``` becomes [ketrenos.com](ketrenos.com).

Cheers,
James

**Comment by BrianOttaway** [comment]
Can I reply via email?

**Comment by jketreno** [comment]
Well, you can certainly reply to my email @BrianOttaway however I don't know how it manages the threading in GitHub. We shall find out, I reckon :)

James

________________________________

**Comment by jketreno** [comment]
Closing.
