### ISSUE TITLE
Create folder and move over lure design files from wiki

### ISSUE THREAD

**Issue by adreanneb** [MinnowBoard-org/website#222]
move all the lure design files to github from wiki so i can link pages to them. Thanks.

**Comment by adreanneb** [comment]
the overview lure page has different lures on it that the individual pages don't call out.

**Comment by adreanneb** [comment]
@BrianOttaway some of the lures have creative license 4.0. Should we keep that or should everything change to 3.0? Thanks for your extreme knowledge.

**Comment by BrianOttaway** [comment]
The license can't change from its original release, without approval from the licensor. I don't see a need to change...CC-BY-__ 3 or 4 is sufficient. Let's just retain the exact license associated on wiki. If in doubt, I can review further.

**Comment by adreanneb** [comment]
@ebrent8 The lure pages are ready to go once the design files are moved over and i can link to them.

**Comment by ebrent8** [comment]
OK I moved all of the lures which actually had design files or a PDX schematic.  Some did not.  They are now at https://github.com/MinnowBoard-org/design-files/tree/master/expansion-boards-lures

So this one is done?

**Comment by adreanneb** [comment]
dun

**Comment by BrianOttaway** [comment]
stellar. thx

**Comment by ebrent8** [comment]
@adreanneb Will you please verify that whatever license text is located where it's supposed to?  I just moved the linked design files.

**Comment by adreanneb** [comment]
@ebrent8 I copied the license from each lure page so should all be correct!

**Comment by ebrent8** [comment]
verified in PROD
