### ISSUE TITLE
determine if want to move these files over from wiki, then move over

### ISSUE THREAD

**Issue by adreanneb** [MinnowBoard-org/website#224]
https://github.com/MinnowBoard/minnow-max-extras

**Comment by ebrent8** [comment]
Hmmm.  What does this mean?  Is everything over that needs to be, except projects TBD?
What about that Minnow Max Extras link above?  Are we linking to that from our new MB MAX page?

**Comment by adreanneb** [comment]
i think we decided to leave the extras on github where they are, no?

**Comment by ebrent8** [comment]
Yeah that makes sense.  Do we need to link to them from the new MAX page?  Probably?

**Comment by adreanneb** [comment]
there's a link to the calamari section in there, but not sure how else to reference it

**Comment by ebrent8** [comment]
Hmmmm yeah.  I don't know.  @BrianOttaway can possibly give direction and value on this.

**Comment by BrianOttaway** [comment]
Item closed...we will keep the old Github project.
