### ISSUE TITLE
Determine what content to move from wiki to website

### ISSUE THREAD

**Issue by adreanneb** [MinnowBoard-org/website#23]
After google analytics review, determine what we are moving over to the new site.

**Comment by dbkinder** [comment]
Need to decide what role the wiki.minnnowboard.org site has going forward.  Are we moving interesting content and shutting down the wiki?

**Comment by ebrent8** [comment]
Agreed.  We need to decide this.  IN Jan we will meet to decide what should go where and how.  We'd love everyone's opinion and expertise on this subject.  I know that the older Max info is valuable to some of the community.

**Comment by ebrent8** [comment]
Let's go over the info that @dbkinder is identifying at the next content meeting.

**Comment by ebrent8** [comment]
We have everything except 'Projects' which Brian is going to assess.
