### ISSUE TITLE
Change /get-a-board URL 

### ISSUE THREAD

**Issue by BrianOttaway** [MinnowBoard-org/website#257]
On /get-a-board page, Change "Netgate" URL for the "MinnowBoard Turbot Dual Core". 
FROM: https://store.netgate.com/Turbot.aspx
TO: https://store.netgate.com/Turbot2.aspx

*WHY: Netgate is out of stock of the Turbot A DC and has a separate SKU/URL for the Turbot B dual-core.

![image](https://cloud.githubusercontent.com/assets/22825861/23435779/32052712-fdbd-11e6-89f3-b47e6131d0ee.png)

**Comment by ebrent8** [comment]
verified in PROD
