### ISSUE TITLE
URLs in Board Explorer are not links, just text

### ISSUE THREAD

**Issue by jketreno** [MinnowBoard-org/website#28]
The links in the board explorer content do not render as links, they are just text.  They should be clickable links.

For example, go to the board viewer and select the ethernet port.  Scroll down in the popup content to see the links.  There are links on many of the board parts to go through and find.
https://www.minnowboard.org/board-viewer

<img width="1273" alt="screen shot 2016-12-06 at 1 37 18 pm" src="https://cloud.githubusercontent.com/assets/18618930/20944706/54f07f88-bbb9-11e6-88fd-bb644e88093d.png">

@ebrent8 Moved this issue here from [bugs-and-help](https://github.com/MinnowBoard-org/bugs-and-help/issues/3)

**Comment by ebrent8** [comment]
Is this just an issue of the links in json are not .md links?  Can we fix this in content?

**Comment by jketreno** [comment]
It is in the .md files; at some point we had to turn off the auto-URL detection because the site was wrapping every instance of `minnowboard.org` with a hyper-link. @juliocri might have found a way to keep that from occurring; if so, then we could turn auto-URL detection back on and these markdown files would auto-URLify again..

If we can't turn auto-URL back on, the .md files need to have URLs explicitly called out:

```text
[https://en.wikipedia.org/wiki/Ethernet](https://en.wikipedia.org/wiki/Ethernet)
```

The specific page linked to from this issue is:

https://github.com/MinnowBoard-org/website/blob/master/global-docs/ethernet.md

(Found by running the site with ?edit=true in the URL)

**Comment by ebrent8** [comment]
OK.  Sounds like it is in progress.

**Comment by juliocri** [comment]
@ebrent8 I think @jketreno in his previous comment tell you how to set the links only changing the content... I just sent to master the change, right now in Stage seems like in the next screenshot:

![screen shot 2017-04-18 at 14 02 38](https://cloud.githubusercontent.com/assets/8356225/25148289/f8810bb0-243f-11e7-8de0-56cf5b193c9d.png)

**Comment by juliocri** [comment]
@ebrent8 let me know when this change is in production in order to close this issue.

**Comment by ebrent8** [comment]
Will do.  I added the 'staged' label which we can check in PROD later this week with some other changes.  Thx.

**Comment by ebrent8** [comment]
@juliocri This is now in PROD, please verify and close if it's complete.  Thanks.

**Comment by ebrent8** [comment]
Fixed and verified in PROD
