### ISSUE TITLE
Add metatags for SEO

### ISSUE THREAD

**Issue by noelianunez** [MinnowBoard-org/website#29]
Google Search Console:
< meta name="google-site-verification" content="ItC7g2v9pxJGO8ArKGBGNKrSGRYJcNyuRsoQ_nooYl8" / >

Add general meta tags like title, etc
Add Open Graph meta tags for social sharing

**Comment by jketreno** [comment]
@noelianunez Do you have a template for how to do both of the above and we'll get it added to the site.

For the Google search console -- is that <meta> tag one that we would add to the index.html?

**Comment by noelianunez** [comment]
@jketreno yes I do have, actually I already had the change but was delayed because it will have the same title everywhere and wont change dinamically. Daniel Serna told me he has the implementation for that but couldn't tested since he does not have his local env settled up, I can ask him tomorrow.

These are the metatags needed:

  <meta name="google-site-verification" content="ItC7g2v9pxJGO8ArKGBGNKrSGRYJcNyuRsoQ_nooYl8" />

  
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">

  
  <meta name="description" content="Meet the MinnowBoard Turbot - compact and affordable open source hardware platform that puts the power of a 64-bit Intel® Atom™ E38xx Series System on a Chip">
  <meta property="og:title" content="MinnowBoard" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="https://minnowboard.org/theme/images/logo.svg" />
  <meta property="og:image" content="http://ia.media-imdb.com/images/rock.jpg" />
  <meta name="og:description" content="Meet the MinnowBoard Turbot - compact and affordable open source hardware platform that puts the power of a 64-bit Intel® Atom™ E38xx Series System on a Chip">

**It's supposed to change the URL and the Description everytime you load a new page/section in the site** but I wasn't sure how to do it. If you keep it static, you will always see the same title and desc while sharing or searching.

For Google search console you can add this metatag
<meta name="google-site-verification" content="ItC7g2v9pxJGO8ArKGBGNKrSGRYJcNyuRsoQ_nooYl8" /> and you let me know so that I can verify its identity directly on the Google Search Console.

**Comment by jketreno** [comment]
From a conversation with @noelianunez -- I will modify the back-end to dynamically inject route specific meta-tags when inbound routes are requested. For example, if someone directly loads https://minnowboard.org/board-viewer it will inject meta-tags specific to that route into the index.html that is returned to the client. This should allow search engines and open graph tags to work.

Implementation wise, there will be `meta-tags.json` file defines the route => meta-tag mapping. Adding new routes and meta-tags can then be edited in that file. The app.js server will use that content to inject into the outbound page.

Example content of meta-tags.json:
```text
[ {
  "route": "/board-viewer",
  "meta-tags": [
    "name='description' content='Interactively explore the MinnowBoard Turbot''",
    "property='og:title' content='MinnowBoard'",
    ...
  ]
}, {
...
} ]
```
@noelianunez @dasernam Comments on the above / syntax / or implementation plan?

**Comment by jketreno** [comment]
Since the website is optimized using `polymer build`, the meta-tag injection will need to be done on a template sequence that isn't removed during the build process. For the `<base href="/">` tag we currently use `<script>'base href="/"';</script>`. We can do something similar for the meta-tags, putting the following at the top of index.html:

```html
<script>'{{meta-tag-injection}}';</script>
```

app.js can then regexp scan the contents being returned for top level routes that would otherwise return `index.html` and inject the meta-tags into the stream.

**Comment by ebrent8** [comment]
@adreanneb has the meta desc and keyword text for the site pages once this is ready.  Thx.
