### ISSUE TITLE
Need redirect for box URL

### ISSUE THREAD

**Issue by ebrent8** [MinnowBoard-org/website#30]
The Turbot box will have the URL www.minnowboard.org/setup printed on it.

We need that URL to redirect to a NEW tutorial which is currently being written titled Getting Started.  Here is the URL.  I will submit the pull request to add this new tutorial today.

https://minnowboard.org/tutorials/getting-started

**Comment by ebrent8** [comment]
ODX - you may need @jketreno or @lilybec assistance on this redirect.

**Comment by ebrent8** [comment]
@jketreno I can think of a few ways to do this.  Not sure which one you want to do.
If you want to do a simple HTML page with GA and a redirect index.htm page, I can implement that.  Just let me know.  

But maybe you want an .htaccess or server-side solution though?

**Comment by jketreno** [comment]
Easiest and fastest for users hitting the site to add a route to the server express app in `app.js`:

```javascript
app.use(basePath + 'setup', function(req, res, next) {
  res.redirect(basePath + 'tutorials/getting-started');
});
```

The express app doesn't require a traditional webserver to be running (eg., apache or nginx) so there is no `.htaccess`.

**Comment by ebrent8** [comment]
Ok cool.  I'll let you or ODX do that since I haven't played with the app.js stuff yet.  Thx.
