### ISSUE TITLE
Site loads very slow on some browsers / connections

### ISSUE THREAD

**Issue by jketreno** [MinnowBoard-org/website#32]
Some users are reporting very slow load times for the website; it sits for a long time fetching/loading the Polymer assets, most notably on Firefox.

We need to run some profiling of the site to see where the delays are coming from and improve the responsive loading.

**Comment by ebrent8** [comment]
Some small things which may help:
- enable GZIP on the server
- the board photo on the homepage is more than 200kb.  it could be reduced to a fraction of that.

**Comment by jketreno** [comment]
@ebrent8 It isn't transfer bandwidth; it is the number of round trips of assets that need to be collected before the site can begin rendering.

Vulcanizing looks like it could give the largest improvement. There are articles on the topic:

https://www.polymer-project.org/1.0/docs/tools/optimize-for-production

**Comment by jketreno** [comment]
I pushed some changes to the `build-optimize` branch to support using `polymer build` however there are style issues with the resulting site.

**Comment by jketreno** [comment]
Fixed the style issues; was a bug in vulcanize (https://github.com/Polymer/vulcanize/issues/375) -- now fixed in fix-32 branch.

**NOTE:** This requires `polymer build` being run on the project to vulcanize and optimize the web resources into a single bundle. The webhook script `sync` currently does not run `polymer build` after the GIT project is pulled. See issue #48.

**Comment by jketreno** [comment]
In addition to `polymer build` needing to be run, the pm2 environment needs to change BASE from `/` to `build/bundled/` when this branch is merged into `master` and then when moved to `production`.

**Comment by jketreno** [comment]
Prior to merging in this fix, loading the website resulted in:
```
159 requests, 1.8MB transferred, 2.31s
```

After `polymer build` was run against the site, it loads with the following:
```
28 requests,  928KB transferred, 1.29s
```
