### ISSUE TITLE
Tutorials - review and update the board option for each

### ISSUE THREAD

**Issue by adreanneb** [MinnowBoard-org/website#341]
![image](https://cloud.githubusercontent.com/assets/24276479/23761579/23984c30-04a8-11e7-835a-08d6071aa975.png)

**Comment by BrianOttaway** [comment]
@ebrent8 , @adreanneb : What do you think about precedence here? My inclination is opt1 or opt2...explicitly stating the board names makes it clear, doesn't rely on users to interpret "compatible" statements, and would this support later filtering? Opt 2 if we were limited in space. Also, seems logical if board titles were URL links to the board landing page (learn-more?). 

- Option 1: (list all boards individually)
  - Board: MinnowBoard Max, Turbot DC, Turbot QC. 
- Option 2: (list all without "MB" prefix)
  - Board: Max, Turbot DC, Turbot QC. 
- Option 3: 
  - Board: Max and Turbot compatible boards.

**Comment by BrianOttaway** [comment]
What is in PROD right now looks right...though I would go ahead and add Max to all with Turbot

**Comment by adreanneb** [comment]
I like option 2. "Compatible" just adds another step for user if they aren't sure. I will add MAX to all

**Comment by ebrent8** [comment]
I agree with @adreanneb

**Comment by BrianOttaway** [comment]
Cool. it's settled.

**Comment by adreanneb** [comment]
all now say MAX and Turbot, except Getting Started which says "MAX and Turbot dual- and quad-core"
