### ISSUE TITLE
resetTab is throwing an exception when changing tabs

### ISSUE THREAD

**Issue by jketreno** [MinnowBoard-org/website#342]
![image](https://cloud.githubusercontent.com/assets/742584/23763482/a462f544-04ae-11e7-81c4-0e315523f756.png)

@juliocri Looks like commit 9d96af6b might have been the change that introduced a JS exception when changing tabs; go to the board-viewer, then back to the main page and the exception gets thrown. Hopefully a quick fix; I'm in the middle of some other code and can't diverge mental topics right now :)

Thanks,
James

**Comment by juliocri** [comment]
@jketreno ready, i just sent the change, i forgot to validate the property before...
