### ISSUE TITLE
Review site for wiki links and edit

### ISSUE THREAD

**Issue by adreanneb** [MinnowBoard-org/website#356]

**Comment by ebrent8** [comment]
I will work with you on this.  There are some remaining links to some wiki info that we didn't pull over yet.   The links are in the board explorer popup tab info.  I'll get a list of which tabs and what info they point to for the next content meeting.

**Comment by ebrent8** [comment]
**Links to wiki I missed:**
- https://stg.minnowboard.org/  footer / **fixed on STG**
- pages/attributions.md  : I don't think this content is live on the site, should it be?
- tuts/powering on minnowboard : http://wiki.minnowboard.org/UEFI
- pages/learn-more-intro.md - **fixed on STG**
