### ISSUE TITLE
git pull didn't run on production push

### ISSUE THREAD

**Issue by jketreno** [MinnowBoard-org/website#42]
A change to `production` didn't successfully change the changes on the production site.

**Comment by ebrent8** [comment]
Also the redirect from app.js doesnt seem to be working.  Or maybe it's a browser cache issue on my side.  Can you verify?  Thx

https://www.minnowboard.org/setup

**Comment by jketreno** [comment]
Please clear your browser cache and try again. If that doesn't work, try using Incognito mode, or a different browser. Let us know what you discover.

**Comment by ebrent8** [comment]
OK yes working now.  I tried it in a new incognito window, so not sure what the problem was.  Maybe cache, maybe DNS or something?  Anyway, it's working now.  Thx.

**Comment by jketreno** [comment]
The Webhook was pointing to http://minnowboard.org/sync instead of https://minnowboard.org/sync. The auto-sync to production occurred with the latest merge request. Closing.
