### ISSUE TITLE
Remove Lures list from Get A Board page

### ISSUE THREAD

**Issue by ebrent8** [MinnowBoard-org/website#422]
We currently list some of the Lures on the Get A Board page:
https://stg.minnowboard.org/get-a-board

We should remove that list of them and point users to our new and awesome LURES page instead of having duplicated content.

**Comment by ebrent8** [comment]
Should we put a section title after Accessories for the Expansion Lures and link to that page from there?
https://minnowboard.org/get-a-board

**Comment by adreanneb** [comment]
it's under there already--you just mean make it a title?

Get Accessories

Before getting started with your board, you will need these recommended components. Purchase them from the below retailers or from one of your choice. Make sure to follow the listed requirements when buying the parts.

For information on expansion boards (lures) available for purchase, see the Lures page.

**Comment by adreanneb** [comment]
Like this?
https://stg.minnowboard.org/get-a-board

**Comment by ebrent8** [comment]
yes cool perfect !
