### ISSUE TITLE
Unlear language in tuturial 'installing Ubuntu 16.04'

### ISSUE THREAD

**Issue by Mark-van-der-Pol** [MinnowBoard-org/website#424]
"At this point, you can use the MinnowBoard Turbot as you would a desktop PC.
_Expose_ the Ubuntu interface, check out the installed programs and file system, open a shell prompt (terminal) and play with the linux command-line shell, and more."

I suspect the word "Expose" was meant to be 'Explore'

**Comment by ebrent8** [comment]
Yes, agreed.  I'll fix it now.  Thx.
