### ISSUE TITLE
Change references to 8GB SD Card to 16GB preferred.

### ISSUE THREAD

**Issue by BrianOttaway** [MinnowBoard-org/website#450]
added per @Mark-van-der-Pol

**Comment by ebrent8** [comment]
Changed to 16 GB and staged on the Ubuntu tutorial.
The accessories says 8 GB (16GB recommended).

**Comment by adreanneb** [comment]
@ebrent8 are there any other instances of this?

**Comment by ebrent8** [comment]
Not that I could find.  The get a board page says 8GB (16 GB recommended).  Apart from that, the Ubuntu tut mentioned 8 GB which I changed to 16.  I think we are good.  Except for this cold rain which never goes away.  But that's another story and I digress ...

**Comment by ebrent8** [comment]
fixed in prod
