### ISSUE TITLE
`polymer build` needs to be run after `git pull` when pushing to staging/production

### ISSUE THREAD

**Issue by jketreno** [MinnowBoard-org/website#48]
In order for the website to be vulcanized, the last step of pushing to the server is to run `polymer build` on the project. The `polymer-cli` needs to be installed on the server, and the `sync` script needs to be updated to perform that task prior to exiting.

**Comment by ebrent8** [comment]
Just to be clear, this is for PROD only.  Local DEV updates etc stay the same?   Thx.

**Comment by jketreno** [comment]
Yes. I was able to work around some idiosyncrasies of the polymer build chain so we can continue doing local dev by launching `npm start` (don't provide the `/` that used to be required)

I ran the `polymer build` after pushing to production, so this bug can be closed.

**Comment by ebrent8** [comment]
Cool I see these new updates to the instructions, thanks !
