### ISSUE TITLE
add email validation to help form

### ISSUE THREAD

**Issue by ebrent8** [MinnowBoard-org/website#503]
The help email address field on the help page is required but needs email validation.  This will help to ensure that an email address with  'zzzz@zzz.com' will work but 'sadf' will not.

https://stg.minnowboard.org/help

This may be the way to do it or you may have a better way.
https://www.webcomponents.org/element/PolymerElements/gold-email-input

**Comment by noelianunez** [comment]
@ebrent8 Fix sent to master, can you verify in stg? Thanks =)

**Comment by ebrent8** [comment]
Looks good on STG.  Working as expected.  Thanks.
