### ISSUE TITLE
Add CPU family codename to CPU description

### ISSUE THREAD

**Issue by jketreno** [MinnowBoard-org/website#51]
We should add the CPU family code name to the CPU description since it is referenced via that code name on various websites and projects. For example, we could use verbiage like:

```
Atom E3826 dual- or E3845 quad-core, part of the BayTrail family of SoCs…
```

The file that needs to be loaded can be linked by clicking `View on GitHub` at the bottom of [CPU context tab](https://stg.minnowboard.org/board-viewer/minnowboard_turbot_B_41/CPU?edit=on)

**Comment by ebrent8** [comment]
@BrianOttaway or @adreanneb Who will write the exact copy that we need for this description?  I do not know this information, but will fix the website when we get it. Thx.

**Comment by BrianOttaway** [comment]
This is what I'd suggest for the Turbot board explorer: [/Turbot_B_41/docs/CPU.md](https://github.com/MinnowBoard-org/website/blob/master/boards/minnowboard_turbot_B_41/docs/CPU.md): 

>The MinnowBoard Turbot board is available in two CPU configurations, either a dual- or quad-core system-on-chip (SoC) from the Intel® Atom™ processor E3800 series, formerly code named BayTrail. See below for more information:
>- [MinnowBoard Turbot](/get-a-board) (dual core): E3826 (1.46 GHz, 1M cache, 7W TDP). [Intel Specs](http://ark.intel.com/products/78477/Intel-Atom-Processor-E3826-1M-Cache-1_46-GHz?q=E3826). 
>- [MinnowBoard Turbot](/get-a-board) (quad core): E3845 (1.91 GHz, 2M cache, 10W TDP). [Intel Specs](http://ark.intel.com/products/78475/Intel-Atom-Processor-E3845-2M-Cache-1_91-GHz?q=E3845#@specifications)

>**Background**: The Intel® Atom™ processor E3800 series, formerly code named BayTrail, consists of 6 SoC [SKUs ](http://ark.intel.com/products/series/78160/Intel-Atom-Processor-E3800-Series#@Embedded) ranging from one to four cores, 512KB to 2M cache, 3W to 10W TDP, and frequency from 1.33GHz to 1.91Ghz. These SoCs are based on the Silvermont microarchitecture, utilizing Intel’s 22nm process technology with 3-D tri-gate transistors, which deliver significant improvements in computational performance and energy efficiency. The E3800 product family is the first system-on-chip (SoC) designed for intelligent systems, delivering outstanding compute, graphical, and media performance while operating in an extended range of thermal conditions. 

>**Design Choice:** For the first MinnowBoard Turbot we liked the sweet spot of the E3826 dual-core at 1.46 GHz, as it meets a broad range of compute applications, has extended temp, a 7W TDP that allows fanless operation under typical loads, and the SoC cost is lower than the quad-core option. There are many other factors we considered, including many that are common across the E3800 series line: AES-NI instructions, graphics, 4-lane PCI express 2.0, virtualization, etc. While the E3826 is a solid BayTrail choice for the above reasons, some of our target developers argued that on a compute-per-gram basis the E3845 quad-core at 10 W TDP is very desirable for applications with heavy compute loads (Robotics, Drones, etc), especially since an E3845 is fully compatible with the E3826 Turbot dual-core firmware and software support. These developers were maxing out the E3826 SoC with compute intensive loads, like spatial imaging and 3D route planning on Robotics/Drones. So, we listened and partnered with ADI Engineering to design the [Turbot quad-core with E3845](/get-a-board).

**Comment by adreanneb** [comment]
[The MinnowBoard Turbot is available in two CPU configurations.docx](https://github.com/MinnowBoard-org/website/files/704858/The.MinnowBoard.Turbot.is.available.in.two.CPU.configurations.docx)

Some suggested edits.

**Comment by BrianOttaway** [comment]
I like Adreanne's reorganization better...It reads better to have the design logic paired with the specs. Also, better to have the BayTrail background and marketing lingo at the bottom.

**Comment by ebrent8** [comment]
Ok I like it too.  I will get it changed on the website right now.

**Comment by ebrent8** [comment]
OK quick question for you all.  Is this new info taking the place of ALL of the existing text or appending on the end of it?

**Comment by ebrent8** [comment]
@jketreno Do you know the answer?  Should that copy replace ALL of the existing text?

**Comment by BrianOttaway** [comment]
Replace it All….ahahaah. (villain-like voice)

**Comment by ebrent8** [comment]
Roger that.  Commencing operation now ...

**Comment by ebrent8** [comment]
Fixed on staging.  @adreanneb please review when you get a chance.  Thx.
https://stg.minnowboard.org/board-viewer

**Comment by adreanneb** [comment]
looks good

**Comment by BrianOttaway** [comment]
NOTE: I did inquire with ADI on availability dates for Dual-E models that should potentially be added to the CPU descriptions. Response pending...Brent copied on email contact.

**Comment by ebrent8** [comment]
Ready for PROD when owner is ready to push.  Thx.

**Comment by ebrent8** [comment]
In PROD
