### ISSUE TITLE
tutorial title and content issue - broken

### ISSUE THREAD

**Issue by ebrent8** [MinnowBoard-org/website#517]
There is an issue with the tutorials and I'm not sure what exactly.  Please look at the last new tutorial on stg: https://stg.minnowboard.org/tutorials

You will see an image for the Auto Grade Linux tutorial at the bottom, but no title or text.  There is an .md file with those elements which do not show up.  You can click on the image thumnail to see the tutorial detail, which is minimal right now.

**This error is blocking us from uploading new tutorials.** Please let me know if this is a content issue or something we can control on the content side.  There are also js console issues, but I couldn't decipher them.  Thank you.

**Comment by juliocri** [comment]
@ebrent8 It could be an issue or not, the rule to extract the summary which is shown in the list was based on get all the content between the first heading and the second one, so... no having a second one, the rule does not work properly, I just sent the change of the rule to stage, now the rule does not care about a second heading. please let me know if this work for you!

**Comment by ebrent8** [comment]
Looks cool.  Thank you for looking at it so quickly.
