### ISSUE TITLE
using markdown for mailto links

### ISSUE THREAD

**Issue by ebrent8** [MinnowBoard-org/website#528]
I don't see an easy way to create mailto links using our version of markdown.
When I try to use either the usual href markdown links like this:
[email us](mailto:support@minnowboard.org)

It doesn't work.  Neither does plain vanilla html.  Am I doing something wrong?  If so can you provide an example please.  Thx.

**Comment by juliocri** [comment]
I'm checking adding the same example (below) in a markdown file:

```[email us](mailto:support@minnowboard.org)```

and based in this example, nothing is wrong with it...

And is working fine, the only weird thing that i noticed was that the mailto-link is always rendered as external link, I just sent the change to avoid that behaviour, and the [email us](mailto:support@minnowboard.org) working fine at  the end of: https://stg.minnowboard.org/help

**Comment by ebrent8** [comment]
fixed in PROD
