### ISSUE TITLE
http://files.minnowboard.org website content

### ISSUE THREAD

**Issue by dbkinder** [MinnowBoard-org/website#57]
Add this to our list of content to examine and either update, move, or delete.  It looks like http://files.minnowboard.org content is actually hosted on the same server as http://wiki.minnowboard.org 184.105.139.132

**Comment by ebrent8** [comment]
Okey dokey, thanks.  Yeah we will have to examine what is valuable.

**Comment by ebrent8** [comment]
@BrianOttaway Which of these files do we want in GitHub or linked from our site?  What's valuable?

**Comment by BrianOttaway** [comment]
My Take:
1. HW-Design
 1. @ebrent8. These are the "minnowboard-v1/rev-a" board files as originally open-sourced by Circuit Co August 2013. Can you copy these over to Github? Then, assign me the issue to get the license file created according to the CC-BY-SA 3.0 unported. 
1. OS-Images:
 1. Omit. Not needed. 
1. PDFs:
 1. @ebrent8 :Save to GDrive for later. No other action needed. 
1. Photos:
 1. @dbkinder has all the originals. Don't need to pull these.

**Comment by ebrent8** [comment]
Mkay thx, I'll get r done.
![mater-git-r-done](https://cloud.githubusercontent.com/assets/18618930/22761562/2338507c-ee10-11e6-811d-30a1f2a6240c.jpg)

**Comment by ebrent8** [comment]
@BrianOttaway All yours for the license file.  Then close this ticket.  Thx.
https://github.com/MinnowBoard-org/design-files

**Comment by BrianOttaway** [comment]
license.md added for rev-a PCB...via commit: 08aaf425c07f38092c6550e0a08c6ad22b1611b8 
Closing this issue.
