### ISSUE TITLE
Add GA tracker

### ISSUE THREAD

**Issue by noelianunez** [MinnowBoard-org/website#59]
Adding missing GA tracker to be able to track events in SPA as mentioned in: https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications

**Comment by ebrent8** [comment]
Is this complete and on STG or PROD?
Are the events firing and showing up in Google Analytics dashboard?

**Comment by juliocri** [comment]
Hi @ebrent8, We are doing some test on it at Stg.

**Comment by ebrent8** [comment]
I think this is live and working now?  If so, feel free to close this issue.

**Comment by noelianunez** [comment]
@ebrent8 yes, it is live =) I will close it, thanks

**Comment by ebrent8** [comment]
Excellent, thank you !

**Comment by jketreno** [comment]
@ebrent8 Re-opening; I just spoke with @noelianunez and @juliocri and we implemented another fix to improve the GA reporting. It is currently active on stg.minnowboard.org and ready for the next batch pull to `production`.

**Comment by ebrent8** [comment]
I assume this is completed and needs to be closed @noelianunez ?
