### ISSUE TITLE
Minnowboard.org Down

### ISSUE THREAD

**Issue by alexanderbeloiu** [MinnowBoard-org/website#592]
Hey, your website minnowboard.org is down, and I can not acess it. It is not a local issue. isitdownrightnow.com also reports that it is down [https://www.isitdownrightnow.com/minnowboard.org.html](url).

**Comment by alexanderbeloiu** [comment]
I found a cached version here [http://web.archive.org/web/20190609034335/https://minnowboard.org/](url)

**Comment by Keiaxx** [comment]
Unfortunately, looking at wayback machine they had a message as show in the image below:

[Imgur](https://imgur.com/qG5ZLnJ)

**Comment by alexanderbeloiu** [comment]
@Keiaxx, thanks, I was wondering what happened. I think the raspberry pi computer made minnowboard go out of bussiness.
