### ISSUE TITLE
What are the allowed values for tutorial "level"?

### ISSUE THREAD

**Issue by adreanneb** [MinnowBoard-org/website#61]
Tutorials have a "Level" attribute that's displayed in the left nav area. To date all the tutorials have been marked as "Starter", but the FTDI-Serial tutorial wants to be marked as "Advanced" (or something that's not "Starter" at least).

What are the allowed values for the tutorial levels?

Moving over Issue #151 gitlab

**Comment by ebrent8** [comment]
Difficulty:  Low
Difficulty:  Medium 
Difficulty:  High

Let's use those.  We just need to change the "Level" field.  I can fix the label and work with ya on it.

**Comment by adreanneb** [comment]
done @ebrent8

**Comment by ebrent8** [comment]
verified in PROD
