### ISSUE TITLE
Add click-thru agreement in order to download board design files.

### ISSUE THREAD

**Issue by adreanneb** [MinnowBoard-org/website#63]
Note: Brian will need to ratify the final language before implementing. Brent and Brian should discuss and edit item description

Reference Designs will be designed to comply with FCC rules, and will have regulatory disclaimer language that a developer needs to click through and accept before downloading files. Suggested verbiage: The files for this reference design do not guarantee regulatory compliance. The developer is responsible for all aspects of regulatory evaluation, reporting and registration when modifying and/or incorporating any element of this reference design into a host device.

moved from github issue 250

**Comment by BrianOttaway** [comment]
Again, the goal here is to provide clear, visible guidance/disclaimer to developers regarding EM emissions and regulatory....all with the end pursuit of best enabling **prototype to end productization** of their design. Thus, the earlier the developer comprehends and acts on regulatory/safety/etc development, the faster/cheaper they get to production. So, we can go with the below text. 

**For download of all design files:**: _Ideally via click-thru (no IP logging needed), but could just post in visible red text next to table of file downloads_
`The files for this reference design do not guarantee regulatory compliance.  The developer is responsible for all aspects of regulatory evaluation, reporting and registration when modifying and/or incorporating any element of this reference design into a host device.`

**Posted as banner on project tutorials, where developers are logically expected to modify their purchased baseboard in some way, by adding daughter cards or breadboard wiring to LSE, etc**
`The resulting design from this tutorial is not guaranteed to comply with regulatory requirements.  The FCC limits quantities of such devices to five or less for personal use.`

Separately, I think it may be helpful to write up a quick "How do I achieve regulatory compliance" tutorial to introduce global regs/ecology/import requirements for production devices. This wouldn't be of much value to experienced professional engineers but may be highly impactful to the developer that has prototyped something cool and wants to get it to production LEGALLY. :) I could write this up later if you stick me with the action.

**Comment by ebrent8** [comment]
@BrianOttaway I believe we solved this with the design files being in GIT now.  It can be closed, correct?

**Comment by BrianOttaway** [comment]
Closed. regs guidance addressed in /design-files readme and license.md files
