### ISSUE TITLE
markdown ordered lists with something other than Arabic digits?

### ISSUE THREAD

**Issue by adreanneb** [MinnowBoard-org/website#68]
In the tutorials I wanted to add some minor steps to an instruction to create something like this:
1. First major step
   a) do this little step first
   b) then this little step
   c) and finally this one
2. Second major step 
But didn't see how to do this unless I used Arabic numbers for the minor steps too, like this:
1. First major step
   1. do this little step first
   2. then this little step
   3. and finally this one
2. Second major step 
This latter form doesn't look very good when rendered. I ended up just using an unordered bullet list for the minor steps, but I would have rather had alphabetic ordered list elements for the sub-steps.
Note this might be handled using CSS on the site that would change the markers used for nested ordered lists to be letters since it looks like the syntax for markdown only allows Arabic numbers to indicate ordered lists.

Issue 105 in gitlab

**Comment by juliocri** [comment]
Hi @adreanneb, you are right markdown syntax only allows Arabic numbers, this is not a default functionality, but we can extend, I remember that some elements can be specified with custom classes such list for example ```{my-class}```, with that we can render the proper style for the list or list item, I let you a link with the examples of list styles that currently exist: http://www.w3schools.com/cssref/pr_list-style-type.asp, see the ***More Examples*** this nomenclature for classes is good what do you think?

**Comment by adreanneb** [comment]
I think that should work @juliocri . Look good to you @dbkinder @ebrent8 ? Thanks!

**Comment by ebrent8** [comment]
Looks good to me.  Just do it!

**Comment by dbkinder** [comment]
ditto.  Transcribing the issue from gitlab to github didn't quite show what was going on with nested lists:

1.  Item One
2.  Item Two
    1. Item Two dot one
    2. Item Two dot two
3. Item Three

I'd like the nested lists (Item two dot one) to use a letter rather than a number so it would look like this:

1.  Item One
2.  Item Two
    a. Item Two dot one
    b. Item Two dot two
3. Item Three

**Comment by juliocri** [comment]
Hey guys @adreanneb, @ebrent8, @dbkinder  I already sent the change to master of the list styles. I'm gonna put an example of how it works, for example if I want to render a list in ```hebrew```,  We can put:

```
1. list-item
2. list-item
3. list-item
{i}
```

OR 

```
1. list-item
2. list-item
3. list-item
{hebrew}
```

As we discussed in a couple of comments above, I'm extending the css styles with the nomenclature in http://www.w3schools.com/cssref/pr_list-style-type.asp (classes from a to v), but further than that we can also put the style name to specified which style will be rendering the list how the second example above.

Also we can define the style for the whole list, but if we need to rewrite an specific list item we can do it, next example render a list with ```hebrew``` style-list, but only the second item will be rendered as a decimal:

```
1. list-item
2. list-item{decimal}
3. list-item
{hebrew}
```
