### ISSUE TITLE
Add the footer to all of the content pages 

### ISSUE THREAD

**Issue by adreanneb** [MinnowBoard-org/website#70]
Not a blocker for MVP, however since the footer contains the feedback link and copyright information, we need to have it available on all of the pages of the site.

Issue 143 in github

**Comment by ebrent8** [comment]
please include the error page at : pages/error-page/

**Comment by ebrent8** [comment]
I think the template needs a new DOM MODULE for the footer info that we can add to every page.  I looked at how the Home page vs the other ones are build, and they seem to differ in that they only load their .MD and not any html or polymer modules.

**Comment by ebrent8** [comment]
This one bugs me to no end.  Moving to Priority_High

**Comment by noelianunez** [comment]
@ebrent8 We have been working on this but is tough since we have the drawer with position absolute it has been a pain to try to place the footer. The only workaround we are able to achieve is placing the footer in the bottom but sticky, it will always be visible. If you want to see this, I can push it to stage so that you can review it.

**Comment by noelianunez** [comment]
@ebrent8 any update on this?

**Comment by ebrent8** [comment]
Nope.  I wasn't able to figure out how to add the footer to every page.  If you, ODX or James can do it, that would be nice.  Thanks.

**Comment by noelianunez** [comment]
@ebrent8 Yes,  I was able to do it but it will be sticky at the bottom of all pages, does that work? I want to confirm that to push it to stage :) thanks!

**Comment by ebrent8** [comment]
Can you push it to stg?  How can I verify and see it?  Thx.

**Comment by noelianunez** [comment]
@ebrent8 I have just push it to stage :) please let me know if it works, otherwise I will remove my commit.

**Comment by ebrent8** [comment]
Thank you.  Hmmmmm.  It takes up more real estate than I imagined.
@jketreno or @juliocri is there any way to have a regular bottom footer?  Even on the home page it seems weird to have it sticky all the time.

**Comment by noelianunez** [comment]
@ebrent8 , @jketreno the issue I came into was that drawer and main have position absolute because of polymer and its functionality so the footer is not placed in the bottom since the main layout does not grow with the content and there is no way to place the footer at the end of the content without been sticky. @jketreno any other idea?

**Comment by acidaniel** [comment]
Flex grid could work for this.

**Comment by jketreno** [comment]
Pushed a commit to https://stg.minnowboard.org that implements a thin footer for all pages except the main landing page, which uses the thicker full footer.

@ebrent8 Let me know your thoughts.

**Comment by ebrent8** [comment]
This will work for now.  Not perfect but better than none at all and better than the fat one.
I say ship it.  Maybe for the MB3 version, we can have a normal bottom footer.
Thank you.

**Comment by adreanneb** [comment]
Looks good. Can we do a line to separate?

Terms of service  |  Privacy  |  Cookies

Feedback  |  Contact

**Comment by jketreno** [comment]
They are currently separated by horizontal whitespace, with visibility and font size based on responsive window width. If we put them on separate lines, we start to get back into having a fat footer taking up screen real estate. Until the footer is part of the scrolling content, vertical space allocated to the footer should be minimized.

Even in a future version that scrolls with the content of the page, the board-viewer would have a static footer permanently taking up screen real esate--perhaps we should take the footer out of that view completely (which is more in line with what other companies do with web applications--eg., google docs, autodesk 360, circuits io, etc.)

**Comment by jketreno** [comment]
OOooooooh! Yeah :) We can do that. My bad.

**Comment by adreanneb** [comment]
thanks @jketreno !

**Comment by ebrent8** [comment]
Hey - we got a text emoji from @jketreno !!!!

**Comment by jketreno** [comment]
New version is pushed to staging with the vertical line break.

**Comment by adreanneb** [comment]
I like it if @ebrent8 thinks it's designly appropriate

**Comment by ebrent8** [comment]
Yep that's cool.  Thx.

**Comment by juliocri** [comment]
@noelianunez, @adreanneb, @ebrent8, @jketreno can we close this issue?

**Comment by ebrent8** [comment]
Yes please, thanks.
