### ISSUE TITLE
MinnowBoard Help page has a horizontal scroll bar on IE and lots of white space at end of page

### ISSUE THREAD

**Issue by adreanneb** [MinnowBoard-org/website#71]
https://sxc.jf.intel.com/minnow/help shows a horizontal scroll bar when using IE that doesn't show up using chrome. Both IE and chrome show lots of (unnecessary) white space at the end of the page (causing a vertical scroll bar to show up)

Big discussion in gitlab issue 191 - still an issue?

**Comment by juliocri** [comment]
@adreanneb I was looking what could be causing the the horizontal scroll, it seems that we need to declare the overflow for IE, I can help with this, but with the vertical scroll I think can not be fixed, due the blank space on the pages is something that help to the slug/anchors functionality and scroll the page to the proper title position.

**Comment by juliocri** [comment]
@adreanneb I just sent the fix for horizontal scroll.

**Comment by adreanneb** [comment]
Thanks @juliocri !
