### ISSUE TITLE
Present board design files in a table with licensing

### ISSUE THREAD

**Issue by adreanneb** [MinnowBoard-org/website#72]
Present board design files under "/Learn-More" in a table. Column 1: design file links, Column 2: "License", Column 3: "What this allows"
Copy the corresponding licensing--or licensing guidance--to appear in columns 2 & 3. "What this allows" guidance should start with "See corresponding CC-BY-__ license for guidance. " then, "In general, this allows you to...."

Issue 205 in gitlab

@BrianOttaway who should do this?

**Comment by BrianOttaway** [comment]
@ebrent8 should be able to establish the columns. We can double check the licensing over call.

**Comment by BrianOttaway** [comment]
Reference bug #63

**Comment by ebrent8** [comment]
@noelianunez We we able to create tables or columns for the website using markdown?  If so, how?  Thx.

**Comment by adreanneb** [comment]
I can do a plain MD table if that's all we need.

**Comment by ebrent8** [comment]
I dunno, we need columns for links and data for this ticket.  How does MD create tables?  Is it in that cheat-sheet that we were looking at earlier?

**Comment by ebrent8** [comment]
I guess if this is supported then yeah we can do it.  No prob.
http://www.tablesgenerator.com/markdown_tables

**Comment by ebrent8** [comment]
I want to sketch out this solution with @BrianOttaway and then we can tackle it.  I'm not clear on the goal visually etc.

**Comment by adreanneb** [comment]
I started making the table, but of the files that I can open, only one listed the license. 

| |  | | 
|----|----|----|
|Design File  | License | What this allows |
| [X205 Schematic](http://wiki.minnowboard.org/images/b/bd/Minnowboard_Turbot_X205_Sch.pdf) (PDF)  |  Creative Commons Attribution-Share
Alike 3.0 Unported License |
| [X205 Bill of Materials](http://wiki.minnowboard.org/images/8/85/Minnowboard_Turbot_X205_BOM.zip)   |  |
| [X205 Schematic and F200 Layout Design Source](http://wiki.minnowboard.org/images/5/5a/Minnowboard_Turbot_F200_X205_VX_Release.zip) (Mentor Graphics Xpedition Enterprise VX)  |  |
| [F200 Gerbers](http://wiki.minnowboard.org/images/a/af/Minnowboard_Turbot_F200_Gerber.zip)   |  |
| [F200 3D Model](http://wiki.minnowboard.org/images/4/42/Minnowboard_Turbot_F200_3D.pdf) (Interactive PDF)   |  |
| [F200 3D Model](http://wiki.minnowboard.org/images/e/ec/Turbot_F200_Board_STEP.zip) (STEP File)   |  |
| [F200 STEP Library](http://wiki.minnowboard.org/images/9/9e/Turbot_F200_STEPLibrary.zip) (STEP File)   |  |

**Comment by adreanneb** [comment]
@ebrent8 
All design files are released under Creative Commons CC BY-SA 3.0 (https://creativecommons.org/licenses/by-sa/3.0/). Read about what this license allows for on the Creative Commons website.  

@ebrent8 @BrianOttaway Not sure if you want to tackle issue 63 at the same time?

**Comment by adreanneb** [comment]
Don't use the url but actually link to with "CC BY-SA 3.0" text

**Comment by ebrent8** [comment]
okee dokey.  I'll take a shot at it and send ya something to look at and review later.  THx.

**Comment by ebrent8** [comment]
@BrianOttaway These links for the ZIP files etc all go to the wiki.  Are we going to move these files under our new website - now or in the future?

**Comment by BrianOttaway** [comment]
The files should ALL be moved to the website or to Github Repo. Creating a new "Board Design Files" Repo would be an easy way to manage file versions and for users to add augmenting files/updates later.  ==> My preference is Github. Thoughts?

**Comment by jketreno** [comment]
I like the idea of a design files repo -- would be a great place to then have expansion board directories for those as well.

**Comment by BrianOttaway** [comment]
Bingo. Brent: let's do this tomorrow.

On Jan 30, 2017, at 7:02 PM, James Ketrenos <notifications@github.com<mailto:notifications@github.com>> wrote:


I like the idea of a design files repo -- would be a great place to then have expansion board directories for those as well.

**Comment by ebrent8** [comment]
OK yes let's do this today and agree on the file structure.  Once we do, I'll move the current Turbot stuff over and link the table of docs to the new repo.

**I was thinking something like this:**

minnowboard.org/

/design-files/turbot/  (zip files, pdfs, etc)
/design-files/turbot/expansion/ (lures, etc)

/ design-files/mb3/
/design-files/mb3/expansion/

**What say you guys?  Will that handle current and future design docs?**   Got a better idea?  Lay it on me, I'm open.

**Comment by jketreno** [comment]
> minnowboard.org/

I would prefer them to be in a separate git repo instead of in the website repository. Then issues, features, design discussions, wiki pages, etc. can happen about the individual board designs:

https://github.com/minnowboard-org/design-files/

I do not think e should put any .zip files into the repository. Assets should be committed as separate files. This makes them useful with a git clone without the user then needing to unzip them, it also allows quick and easy access to a LICENSE file in each sub-directory indicating the license those assets are provided under.

Links to the assets from the website can then point to the design-files/ subdirectory containing the content.

I think using the full board name instead of acronyms or partial names will help route users:
```
.../design-files/minnowboard-turbot-b41/
.../design-files/minnowboard-max-a1/
.../design-files/minnowboard-turbot-a/
.../design-files/minnowboard3/
...
```
For expansion boards, since they are intended to be compatible across boards, I would put them in a top level directory with the name aligning to the connector interface:

```
.../design-files/low-speed-expansion/tadpole/
.../design-files/high-speed-expansion/silver-jaw/
...
```

**Comment by BrianOttaway** [comment]
Good comments above. @ebrent8 I think you can move forward:

-I created a new [Design-Files repo](https://github.com/MinnowBoard-org/Design-Files). 
-Use full board names as next tier folders. (I agree with what James proposed):
`.../design-files/minnowboard-3/
.../design-files/minnowboard-turbot-dual-core-revX205/ (in notes call out "Rev X205 (PCB Rev F200)" and ADI mfr PN)
.../design-files/minnowboard-turbot-quad-core/
.../design-files/minnowboard-turbot-dual-e/
.../design-files/minnowboard-v1/
.../design-files/minnowboard-max-rev-a1
.../design-files/minnowboard-max-rev-a2`

-proceed with LSE and HSE folders like James suggested above.
-under each board folder we need some kind of license file or readme to clearly call out: licensing and corresponding manufacturer part number for the board.
-we can sync on which Lures files to pull in from the [old MB Github](https://github.com/MinnowBoard). Some, but only the officially supported Lures. Non-official (meaning not validated or reviewed for EMI/EMC/Safety) Lures will have to stay separate, out of official /MB-org github.
-bueno. :)

**Comment by BrianOttaway** [comment]
@ebrent8. Regarding Disclaimers for the Board files, I will add this under the readme and repo description. At minimum we need to reflect some legalese, like: 

> The files for this reference design do not guarantee regulatory compliance.  The developer is responsible for all aspects of regulatory evaluation, reporting and registration when modifying and/or incorporating any element of this reference design into a host device.

**Comment by ebrent8** [comment]
Hmmmm I'm halfway clear with this.  So some of our docs are in a ZIP.  Do we not want them zipped and linked like we currently do for Turbot?

https://minnowboard.org/learn-more
(links at bottom of that page)

**Comment by BrianOttaway** [comment]
I'd propose that we have no .zip files...unzip them and put them in repo.

**Comment by ebrent8** [comment]
OK.  I'll do one and let you check it out to see if it's what you want.

**Comment by ebrent8** [comment]
<img width="334" alt="screen shot 2017-01-31 at 2 18 29 pm" src="https://cloud.githubusercontent.com/assets/18618930/22486906/3791e0de-e7c0-11e6-8f77-b90dbd6e2ba9.png">
