### ISSUE TITLE
Host board design files and collateral on the website, outside of GIT

### ISSUE THREAD

**Issue by adreanneb** [MinnowBoard-org/website#73]
@dbkinder  is this considered part of the important move over from wiki items?

issue 222 in gitlab

**Comment by ebrent8** [comment]
The design files are being moved over today.  Brian and James are chiming in on how we organize them behind the scenes.  But yes the Turbot design files are moving over under the website INSIDE of GitHub.

The rest of the wiki pages - that's a different story.  David and Brian and maybe Chris need to help determine that.

**Comment by ebrent8** [comment]
Done.  They have their own repo under MinnowBoard now.
