### ISSUE TITLE
Internal Intel PDL list and VTM to setup a forward alias from support@minnowboard.org to that PDL

### ISSUE THREAD

**Issue by adreanneb** [MinnowBoard-org/website#77]
We need to setup an alias for support@minnowboard.org to forward to an @intel.com address that the MinnowBoard team can monitor.
@valigatorCA  @brottawa  Do either of you know how to get an @intel.com PDL configured?
Can external entities mail to it? (Emails would be originating from the VTM operated server, sent to that PDL address.)
In addition to listing it as an email contact point, the minnowboard.org/help form will send user questions to that email address.
Right now I can configure the MinnowBoard.org server to send to support@minnowboard.org but those messages won't go anywhere until the aliases are configured.

Issue 239 in gitlab, related to issue 240

**Comment by BrianOttaway** [comment]
@jketreno, @ebrent8 , Can we simply create a new eclists email list and forward to that?...instead of a PDL?

**Comment by jketreno** [comment]
This was resolved by configuring support@minnowboard.org to be configured via a alias on the server to forward to multiple email addresses.

I don't think having a support email address auto forward to a public mailing is a good idea.

**Comment by BrianOttaway** [comment]
So, Close this bug?
