### ISSUE TITLE
External website content - Monitor and/or Update with latest board

### ISSUE THREAD

**Issue by adreanneb** [MinnowBoard-org/website#82]
- https://software.intel.com/en-us/iot/hardware/minnow-board-max
- https://software.intel.com/zh-cn/videos/minnowboard-introduction as well as a Chinese forum
- (https://software.intel.com/zh-cn/forums/intel-platform-based-embedded-software-development/topic/629278)

**Comment by ebrent8** [comment]
We are now rockin the Turbot on the IoT page which will also be translated into multi languages.
https://software.intel.com/en-us/iot/hardware/minnow-board-turbot
