### ISSUE TITLE
Issue reporting link should go directly to the issues tab

### ISSUE THREAD

**Issue by dbkinder** [MinnowBoard-org/website#9]
The "Get Help" page says, "We currently have a project set up in our MinnowBoard.org: GitHub group for filing questions and issues." and links to https://github.com/minnowboard-org/bugs-and-help.  This would be better aimed at https://github.com/minnowboard-org/bugs-and-help/issues

**Comment by jketreno** [comment]
Since the verbiage accurately describes the link, changing the link means we should change the text.

Perhaps:

> We track MinnowBoard.org related issues on our GitHub project "bugs-and-help". Please visit the [issues](https://github.com/minnowboard-org/bugs-and-help/issues) section of that project to submit an issue.

?

**Comment by ebrent8** [comment]
I like it.  Made the change and pushed to stg.

**Comment by ebrent8** [comment]
fixed in ebrent8-fix-9
